package dev.jdtech.jellyfin.presentation.theme

import androidx.compose.material3.darkColorScheme
import androidx.tv.material3.darkColorScheme as darkColorSchemeTv
import dev.jdtech.jellyfin.core.presentation.theme.ColorDark

val darkScheme =
    darkColorScheme(
        primary = ColorDark.primaryDark,
        onPrimary = ColorDark.onPrimaryDark,
        primaryContainer = ColorDark.primaryContainerDark,
        onPrimaryContainer = ColorDark.onPrimaryContainerDark,
        secondary = ColorDark.secondaryDark,
        onSecondary = ColorDark.onSecondaryDark,
        secondaryContainer = ColorDark.secondaryContainerDark,
        onSecondaryContainer = ColorDark.onSecondaryContainerDark,
        tertiary = ColorDark.tertiaryDark,
        onTertiary = ColorDark.onTertiaryDark,
        tertiaryContainer = ColorDark.tertiaryContainerDark,
        onTertiaryContainer = ColorDark.onTertiaryContainerDark,
        error = ColorDark.errorDark,
        onError = ColorDark.onErrorDark,
        errorContainer = ColorDark.errorContainerDark,
        onErrorContainer = ColorDark.onErrorContainerDark,
        background = ColorDark.backgroundDark,
        onBackground = ColorDark.onBackgroundDark,
        surface = ColorDark.surfaceDark,
        onSurface = ColorDark.onSurfaceDark,
        surfaceVariant = ColorDark.surfaceVariantDark,
        onSurfaceVariant = ColorDark.onSurfaceVariantDark,
        outline = ColorDark.outlineDark,
        outlineVariant = ColorDark.outlineVariantDark,
        scrim = ColorDark.scrimDark,
        inverseSurface = ColorDark.inverseSurfaceDark,
        inverseOnSurface = ColorDark.inverseOnSurfaceDark,
        inversePrimary = ColorDark.inversePrimaryDark,
        surfaceDim = ColorDark.surfaceDimDark,
        surfaceBright = ColorDark.surfaceBrightDark,
        surfaceContainerLowest = ColorDark.surfaceContainerLowestDark,
        surfaceContainerLow = ColorDark.surfaceContainerLowDark,
        surfaceContainer = ColorDark.surfaceContainerDark,
        surfaceContainerHigh = ColorDark.surfaceContainerHighDark,
        surfaceContainerHighest = ColorDark.surfaceContainerHighestDark,
    )

val darkSchemeTv =
    darkColorSchemeTv(
        primary = ColorDark.primaryDark,
        onPrimary = ColorDark.onPrimaryDark,
        primaryContainer = ColorDark.primaryContainerDark,
        onPrimaryContainer = ColorDark.onPrimaryContainerDark,
        secondary = ColorDark.secondaryDark,
        onSecondary = ColorDark.onSecondaryDark,
        secondaryContainer = ColorDark.secondaryContainerDark,
        onSecondaryContainer = ColorDark.onSecondaryContainerDark,
        tertiary = ColorDark.tertiaryDark,
        onTertiary = ColorDark.onTertiaryDark,
        tertiaryContainer = ColorDark.tertiaryContainerDark,
        onTertiaryContainer = ColorDark.onTertiaryContainerDark,
        error = ColorDark.errorDark,
        onError = ColorDark.onErrorDark,
        errorContainer = ColorDark.errorContainerDark,
        onErrorContainer = ColorDark.onErrorContainerDark,
        background = ColorDark.backgroundDark,
        onBackground = ColorDark.onBackgroundDark,
        surface = ColorDark.surfaceDark,
        onSurface = ColorDark.onSurfaceDark,
        surfaceVariant = ColorDark.surfaceVariantDark,
        onSurfaceVariant = ColorDark.onSurfaceVariantDark,
        scrim = ColorDark.scrimDark,
        inverseSurface = ColorDark.inverseSurfaceDark,
        inverseOnSurface = ColorDark.inverseOnSurfaceDark,
        inversePrimary = ColorDark.inversePrimaryDark,
    )
